/**
 * One-time, blocking navigation-liability disclaimer. `maybeShowDisclaimer()`
 * is awaited very early in main.ts, before any chart/GPS setup — the app has
 * nothing on screen until the user taps "I Agree".
 *
 * DISCLAIMER_VERSION is independent of the app's package.json version. Bump
 * it (and the text in `buildAgreementBody`) whenever the legal text changes
 * or a chart data source changes in a way that warrants re-acknowledgment —
 * that forces every user to re-accept on their next launch, regardless of
 * whether the app version itself changed.
 */

import { App } from "@capacitor/app";
import { Capacitor } from "@capacitor/core";
import {
  createJsonStorageSlot,
  defaultBrowserStorage,
} from "../utils/json-storage-slot";

declare const __APP_VERSION__: string;

export const DISCLAIMER_VERSION = 2;

interface DisclaimerAcceptance {
  disclaimerVersion: number;
  acceptedAt: number;
  appVersion: string;
}

function isDisclaimerAcceptance(v: unknown): v is DisclaimerAcceptance {
  if (typeof v !== "object" || v === null) return false;
  const r = v as Record<string, unknown>;
  return (
    typeof r.disclaimerVersion === "number" &&
    typeof r.acceptedAt === "number" &&
    typeof r.appVersion === "string"
  );
}

const slot = createJsonStorageSlot<DisclaimerAcceptance>(
  "pelorus-nav-disclaimer-acceptance",
  isDisclaimerAcceptance,
);

/**
 * The stored acceptance record, but only if it's for the *current*
 * disclaimer version — a record from an older version means re-acceptance
 * is required, so callers should treat that as "not accepted".
 */
export function getDisclaimerAcceptance(): DisclaimerAcceptance | null {
  const record = slot.load(defaultBrowserStorage());
  return record?.disclaimerVersion === DISCLAIMER_VERSION ? record : null;
}

function recordAcceptance(): void {
  slot.save(
    {
      disclaimerVersion: DISCLAIMER_VERSION,
      acceptedAt: Date.now(),
      appVersion: __APP_VERSION__,
    },
    defaultBrowserStorage(),
  );
}

function buildAgreementBody(): HTMLDivElement {
  const body = document.createElement("div");
  body.className = "disclaimer-body";
  body.innerHTML = `

    <p class="ua-notice">Please read carefully. This agreement limits your legal
    rights, including your right to sue the developer for negligence.</p>

    <p>This app is provided by Dark Star Systems, Inc.
    (&ldquo;Developer&rdquo;). By tapping &ldquo;I Agree,&rdquo; you enter into a
    binding agreement with Developer and acknowledge the following:</p>

    <h2>1. Navigational aid only</h2>
    <p>This app is an aid to navigation and planning. It is not a substitute for
    official government nautical charts, prudent seamanship, or your own judgment.
    Chart data, GPS positioning, depth soundings, tide and current data, and other
    displayed information may be inaccurate, outdated, or incomplete, and the
    software itself may contain errors, defects, or malfunctions. Any route or
    track generated by this app is a planning suggestion only and
    <strong>must not be used for direct navigation</strong>.</p>

    <h2>2. You are in command</h2>
    <p>You are solely responsible for the safe navigation and operation of your
    vessel and for compliance with all applicable navigation rules and
    regulations. You remain responsible for maintaining official charts and any
    other aids to navigation required for your vessel, and you agree not to rely
    on this app as your sole means of navigation.</p>

    <h2>3. Assumption of risk</h2>
    <p>Navigation involves inherent risks, including grounding, collision, injury,
    death, and loss of or damage to vessels and property. You knowingly and
    voluntarily assume all risks arising from your use of this app, including
    risks caused by inaccurate data or software defects.</p>

    <h2>4. No warranty</h2>
    <p class="ua-caps">This app is provided &ldquo;as is&rdquo; and &ldquo;as
    available,&rdquo; without warranty of any kind, express or implied, including
    without limitation the implied warranties of merchantability, fitness for a
    particular purpose, accuracy, and non-infringement.</p>

    <h2>5. Release and limitation of liability</h2>
    <p class="ua-caps">To the fullest extent permitted by applicable law, you
    release, and agree not to sue, Developer and its owners, officers, employees,
    contractors, and data suppliers for any claim, loss, or damage &mdash;
    including personal injury, death, property damage, grounding, collision, or
    other marine casualty &mdash; arising from your use of, or inability to use,
    this app, <strong>including claims based on Developer&rsquo;s own
    negligence</strong>. If any part of this release is held unenforceable,
    Developer&rsquo;s total liability for all claims shall not exceed the amount
    you paid for the app in the twelve months before the claim arose or US $50,
    whichever is greater. In no event shall Developer be liable for indirect,
    incidental, consequential, special, or punitive damages.</p>

    <h2>6. Indemnification</h2>
    <p>You agree to defend, indemnify, and hold harmless Developer and the parties
    listed above from any third-party claim, and related costs and
    attorneys&rsquo; fees, arising from your use of this app or your operation of
    any vessel.</p>

    <h2>7. Savings and severability</h2>
    <p>Some jurisdictions do not allow certain warranty disclaimers or liability
    exclusions, including for death or personal injury; in those jurisdictions the
    above provisions apply only to the maximum extent permitted, and nothing in
    this agreement excludes liability that cannot lawfully be excluded. If any
    provision is held invalid, the remaining provisions remain in full effect.</p>

    <h2>8. Governing law</h2>
    <p>This agreement is governed by the laws of Massachusetts, without regard to
    conflict-of-laws rules, and any dispute not subject to the release above shall
    be brought exclusively in the state or federal courts located in
    Middlesex County, Massachusetts.</p>

    <p>If you do not agree, tap &ldquo;Decline&rdquo; and do not use this app.</p>
  `;
  return body;
}

/** Show the blocking dialog. Resolves only once the user taps "I Agree". */
function showDisclaimerDialog(): Promise<void> {
  return new Promise((resolve) => {
    const overlay = document.createElement("div");
    overlay.className = "about-overlay disclaimer-overlay";
    overlay.style.display = "flex";

    const card = document.createElement("div");
    card.className = "about-card disclaimer-card";
    overlay.appendChild(card);
    document.body.appendChild(overlay);

    const renderAgreement = (): void => {
      card.replaceChildren();

      const title = document.createElement("div");
      title.className = "about-title";
      title.textContent = "Navigation Warning, Disclaimer & User Agreement";

      const buttons = document.createElement("div");
      buttons.className = "disclaimer-buttons";

      const declineBtn = document.createElement("button");
      declineBtn.className = "screen-timeout-btn";
      declineBtn.textContent = "Decline";
      declineBtn.addEventListener("click", renderDeclined);

      const agreeBtn = document.createElement("button");
      agreeBtn.className = "screen-timeout-btn primary";
      agreeBtn.textContent = "I Agree";
      agreeBtn.addEventListener("click", () => {
        recordAcceptance();
        overlay.remove();
        resolve();
      });

      buttons.append(declineBtn, agreeBtn);
      card.append(title, buildAgreementBody(), buttons);
    };

    const renderDeclined = (): void => {
      card.replaceChildren();

      const title = document.createElement("div");
      title.className = "about-title";
      title.textContent = "Agreement required";

      const body = document.createElement("div");
      body.className = "disclaimer-body";
      body.textContent =
        "Pelorus Nav can't be used without accepting the navigation " +
        "disclaimer.";

      const buttons = document.createElement("div");
      buttons.className = "disclaimer-buttons";

      const reviewBtn = document.createElement("button");
      reviewBtn.className = "screen-timeout-btn primary";
      reviewBtn.textContent = "Review Again";
      reviewBtn.addEventListener("click", renderAgreement);
      buttons.appendChild(reviewBtn);

      // App.exitApp() is Android-only (unimplemented on iOS/web, and Apple
      // guidelines disallow apps quitting themselves) — only offer it there.
      if (Capacitor.getPlatform() === "android") {
        const exitBtn = document.createElement("button");
        exitBtn.className = "screen-timeout-btn";
        exitBtn.textContent = "Exit App";
        exitBtn.addEventListener("click", () => {
          App.exitApp();
        });
        buttons.appendChild(exitBtn);
      }

      card.append(title, body, buttons);
    };

    renderAgreement();
  });
}

/**
 * Show the disclaimer once, blocking until the user agrees. No-op if the
 * user already accepted the currently-running disclaimer version.
 */
export async function maybeShowDisclaimer(): Promise<void> {
  if (getDisclaimerAcceptance()) return;
  await showDisclaimerDialog();
}

/**
 * Read-only view of the agreement the user already accepted (opened from the
 * About dialog's "Terms" link) — same text, but freely dismissible and with
 * no effect on the stored acceptance.
 */
export function showTermsDialog(): void {
  const overlay = document.createElement("div");
  overlay.className = "about-overlay disclaimer-overlay";
  overlay.style.display = "flex";

  const card = document.createElement("div");
  card.className = "about-card disclaimer-card";

  const title = document.createElement("div");
  title.className = "about-title";
  title.textContent = "Navigation Warning, Disclaimer & User Agreement";

  const onKeydown = (e: KeyboardEvent): void => {
    if (e.key === "Escape") {
      e.preventDefault(); // consumed — the global Escape fallback must not also act
      close();
    }
  };
  const close = (): void => {
    document.removeEventListener("keydown", onKeydown);
    overlay.remove();
  };

  const buttons = document.createElement("div");
  buttons.className = "disclaimer-buttons";
  const closeBtn = document.createElement("button");
  closeBtn.className = "screen-timeout-btn primary";
  closeBtn.textContent = "Close";
  closeBtn.addEventListener("click", close);
  buttons.appendChild(closeBtn);

  card.append(title, buildAgreementBody(), buttons);
  overlay.appendChild(card);
  overlay.addEventListener("mousedown", (e) => {
    if (e.target === overlay) close();
  });
  document.addEventListener("keydown", onKeydown);
  document.body.appendChild(overlay);
}
