#!/usr/bin/env bun
/**
 * Convert a Pelorus GPX track into the simulator replay track
 * (src/navigation/replay-track.ts): compact [tSec, lat, lon] tuples,
 * timestamps relative to the first point. Re-run to swap in a new track:
 *
 *   bun tools/gpx-to-replay.ts ~/path/to/Track.gpx
 */

import { readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const gpxPath = process.argv[2];
if (!gpxPath) {
  console.error("Usage: bun tools/gpx-to-replay.ts <track.gpx>");
  process.exit(1);
}

const xml = readFileSync(gpxPath, "utf8");
const re =
  /<trkpt\s+lat="([-\d.]+)"\s+lon="([-\d.]+)">[\s\S]*?<time>([^<]+)<\/time>/g;

const points: [number, number, number][] = [];
let t0: number | null = null;
for (const m of xml.matchAll(re)) {
  const lat = Number(m[1]);
  const lon = Number(m[2]);
  const ms = Date.parse(m[3]);
  if (!Number.isFinite(lat) || !Number.isFinite(lon) || Number.isNaN(ms)) {
    continue;
  }
  t0 ??= ms;
  const t = Math.round((ms - t0) / 1000);
  // Skip duplicate timestamps (zero-length segments)
  if (points.length > 0 && t <= points[points.length - 1][0]) continue;
  points.push([t, Number(lat.toFixed(5)), Number(lon.toFixed(5))]);
}

if (points.length < 2) {
  console.error(`Only ${points.length} usable trkpts found — aborting`);
  process.exit(1);
}

const durationH = (points[points.length - 1][0] / 3600).toFixed(1);
const body = points.map((p) => `  [${p[0]}, ${p[1]}, ${p[2]}],`).join("\n");
const out = `/**
 * Simulator replay track — a real recorded sail, for realistic GPS-pipeline
 * testing (true turn rates, accelerations, and pauses).
 *
 * Generated by tools/gpx-to-replay.ts from "${basename(gpxPath)}"
 * (${points.length} points, ${durationH} h). Regenerate with:
 *   bun tools/gpx-to-replay.ts <track.gpx>
 */

/** [seconds since track start, latitude, longitude] */
export const REPLAY_TRACK: [number, number, number][] = [
${body}
];
`;

const outPath = join(import.meta.dirname, "../src/navigation/replay-track.ts");
writeFileSync(outPath, out);
console.log(
  `Wrote ${outPath}: ${points.length} points, ${durationH} h, ${(out.length / 1024).toFixed(0)} KB`,
);
