#!/usr/bin/env bun
// Stamp package.json's version into ios/version.xcconfig (gitignored,
// generated) so the marketing version stays in sync across web / Android /
// iOS from one source of truth — without ever touching the committed Xcode
// project file. The App target's Release config uses version.xcconfig as its
// base configuration; Debug picks it up via the include in debug.xcconfig.
//
// The build number (CURRENT_PROJECT_VERSION) is deliberately NOT touched here —
// it derives from the git commit count and is injected at build time by the CI
// workflow and tools/ios-beta.sh (both also override MARKETING_VERSION on the
// xcodebuild command line, so this file only feeds local builds).
//
// Runs automatically before every iOS build via the cap:*:ios package scripts.

import { readFileSync, writeFileSync } from "node:fs";

const XCCONFIG = "ios/version.xcconfig";

const version = JSON.parse(readFileSync("package.json", "utf8"))
  .version as string;
const next = `// Generated by tools/sync-ios-version.ts — do not edit or commit.\nMARKETING_VERSION = ${version}\n`;

let prev = "";
try {
  prev = readFileSync(XCCONFIG, "utf8");
} catch {}
if (prev === next) {
  console.log(`iOS MARKETING_VERSION already ${version}`);
} else {
  writeFileSync(XCCONFIG, next);
  console.log(`Set iOS MARKETING_VERSION = ${version}`);
}
